In [5]:
# Run this cell to set up your notebook
import seaborn as sns
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
sns.set()
sns.set_context("talk")
from datascience import *
plt.style.use("fivethirtyeight")


from IPython.display import display, Latex, Markdown

In [9]:
data=pd.read_csv("2018_Conainer_visData.csv")
data

,imo,hour,draught,long_x,lat_x,sog_x,cog,obsType,Ship_Class,InECA,PortStop,Eca_Name,PortCountry,head_port,head_port_iso3,Size_Bin,EM_CO2_LNG,EM_CO2,Built
0,7033161,0,0.0,-99999.000000,-99999.000000,0.00,-99999.0,Missing,Container,0,0,None,None,NaN,None,1,713212.500000,807615.900000,1971
1,7033161,1,0.0,-99999.000000,-99999.000000,0.00,-99999.0,Missing,Container,0,0,None,None,NaN,None,1,713212.500000,807615.900000,1971
2,7033161,2,0.0,-99999.000000,-99999.000000,0.00,-99999.0,Missing,Container,0,0,None,None,NaN,None,1,713212.500000,807615.900000,1971
3,7033161,3,0.0,-99999.000000,-99999.000000,0.00,-99999.0,Missing,Container,0,0,None,None,NaN,None,1,713212.500000,807615.900000,1971
4,7033161,4,0.0,-99999.000000,-99999.000000,0.00,-99999.0,Missing,Container,0,0,None,None,NaN,None,1,713212.500000,807615.900000,1971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45131650,9854662,8755,3.5,125.173790,1.425128,0.05,65.3,Present,Container,0,1,None,IDN,BITUNG,IDN,1,408237.621885,475930.842095,2018
45131651,9854662,8756,3.5,125.173698,1.425256,0.05,65.3,Present,Container,0,1,None,IDN,BITUNG,IDN,1,408237.621885,475930.842095,2018
45131652,9854662,8757,3.5,125.173840,1.425092,0.10,65.3,Present,Container,0,1,None,IDN,BITUNG,IDN,1,408238.475076,475931.836761,2018
45131653,9854662,8758,3.5,125.173882,1.424985,0.00,65.3,Present,Container,0,1,None,IDN,BITUNG,IDN,1,408237.500000,475930.700000,2018
45131654,9854662,8759,3.5,125.173230,1.425340,0.20,65.3,Present,Container,0,1,None,IDN,BITUNG,IDN,1,408245.300586,475939.794065,2018

In [ ]:
conda install geopandas

Collecting package metadata (current_repodata.json): done
Solving environment: \

In [11]:
import geopandas as gpd
import geoplot as gplt
import geoplot.crs as gcrs
from shapely.geometry import Point

ModuleNotFoundError: No module named 'geopandas'

In [10]:
# Converting our dataset into a GeoDataFrame using geopandas for plotting using the geoplot library
data_geopandas_points = data.apply(
    lambda srs: Point(float(srs['long_x']), float(srs['lat_x'])),
    axis='columns'
)
data_geopandas = gpd.GeoDataFrame(data, geometry=data_geopandas_points)

Class = gpd.read_file(gplt.datasets.get_path('Ship_Class'))

NameError: name 'Point' is not defined